cfg = {
thingspeak_enable=0,
ap_pwd=1234567890,
thingspeak_api_key="",
web_id=1,
ap_ssid="MeteoStation",
web_key="AAAABBBBCCCCDDDD",
web_url="http://your-site.com/meteo/meteo.php",
thingspeak_url="api.thingspeak.com",
data_file_max_size=120000,
wifi_ssid="WiFi_SSID",
web_enable=0,
web_queue_file="queue.txt",
data_file="log.txt",
data_file_lines=2976,
wifi_pwd="********",
cron_mask="*/15 * * * *",
}
